[package]
name = "password-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
rand = "0.8.5"
serde = { version = "1.0.214", features = ['derive'] }
serde_json = "1.0.132"
uuid = { version = "1.11.0", features = ["fast-rng", "v4"] }
